Fix error in readme example.
Example in readme gives following error:
    bm.start_aggtrade_socket(symbol='BNBBTC')
TypeError: start_aggtrade_socket() missing 1 required positional argument: 'callback'